# Unidad 3


## Álgebra Lineal

El álgebra lineal es una disciplina donde se estudian los espacios vectoriales y el mapeo lineal entre ellos. En física y astronomía, varios fenómenos se pueden escribir fácilmente en términos de variables lineales, lo que hace que el álgebra lineal computacional sea un tema muy importante que se cubrirá a lo largo de este curso.

Un hecho interesante del álgebra lineal computacional es que no comprende enfoques numéricos ya que la mayoría de los métodos son exactos. El uso de una computadora es necesario debido a la gran cantidad de cálculos en lugar de la naturaleza no soluble de los problemas. Los errores numéricos provienen luego de aproximaciones de redondeo.


Un sistema lineal es un conjunto de ecuaciones de variables $ n $ que se pueden escribir de forma general:

$$ a_ {11} x_1 + a_ {12} x_2 + \cdots a_ {1n} x_n = b_1 $$
$$ \vdots $$
$$ a_ {m1} x_1 + a_ {m2} x_2 + \cdots a_ {mn} x_n = b_m $$

donde $ n $ es, nuevamente, el número de variables y $ m $ el número de ecuaciones.

## Sistemas lineales de ecuaciones

Un sistema lineal tiene solución si y solo si $ m \geq n $. Esto nos lleva al objetivo principal de un sistema lineal: encontrar el conjunto $ \{x_i \}_{i = 0}^n $ que cumple con todas las ecuaciones.

Aunque hay una forma intuitiva de resolver este tipo de sistemas, simplemente sumando y restando ecuaciones hasta alcanzar el resultado deseado, la gran cantidad de variables de algunos sistemas que se encuentran en física y astronomía hace necesario desarrollar enfoques iterativos y generales. A continuación, presentaremos la notación matricial y vectorial y algunas operaciones básicas que serán la base de los métodos que se desarrollarán en esta sección.

### Matrices y vectores

Una matriz $m\times n$ se puede definir como un conjunto de números dispuestos en columnas y filas como:

$$ A = [a_{ij}] = \left[ \matrix{
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & & \vdots\\
a_{m1} & a_{m2} & \cdots & a_{mn}
}\right] $$

Del mismo modo, es posible definir un vector de columna $ n $ -dimensional como

$$ \textbf{x} = \left[ \matrix{
x_{1} \\
x_{2} \\
\vdots\\
x_{n}
}\right] $$

y un vector de fila

$$ \textbf{y} = \left[ \matrix{
y_{1} &
y_{2} &
\cdots &
y_{n}
}\right] $$

Las rutinas para solución de sistemas lineales y algebra lineal están implementadas como métodos en las librerías `numpy` y `scipy`. Scipy usa librerías optimizadas como ATLAS, LAPACK y BLAS de [algebra lineal](https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html), Numpy también tiene sus propias librerías,
las librerías se importan como,

```python
import scipy.linalg as LA
import numpy.linalg as La
```

o también,

```python
from numpy import *       
from numpy.linalg import *
from scipy.linalg import * # para algunas funciones como lu, lu_solve, etc
```

In [ ]:
from numpy.linalg import *

## Dimensión de  matrices
Un arreglo simple es una matriz de dimensión $n\times1$ o vector, por ejemplo el siguiente array numpy de dimensión 10,
```python
a = array([0,1,2,3,4,5,6,7,8,9])
```
Recordemos que `a == a[:] == a[0:10]`. Para obtener un subarray se usa la siguiente notación,
```python
a[5:8] # da el sub vector array([5, 6, 7])      
```
Por otro lado, las matrices se construyen con arreglos dos dimensiónales (arrays), por ejemplo la siguiente matriz $3\times 3$,
```python
A=array([[0,1,2],[3,4,5],[6,7,8]]) # array([[0, 1, 2],
                                   #        [3, 4, 5],
                                   #        [6, 7, 8]])
```
Para obtener los elementos individuales se usa, `A[i,j]`, donde $i$ barre sobre las filas y $j$ sobre las columnas, así,
```python
print( A[0,0], A[0,1],A[0,2] )
print( A[1,0], A[1,1],A[1,2] )
print( A[2,0], A[2,1],A[2,2] )
```
Note que `A[i,:]` da la fila $i$ y `A[:,j]` da la columna $j$. Ejemplo,

```python
A[1,:]   # fila array([3, 4, 5])
A[:,1]   # columna array([1, 4, 7])
A[1]     # igual que A[1,:]
```
Nota: si `A` es un array 2D, puede simplemente escribir `A[i]` para obtener la fila $i$.

## Submatrices
Con la notación anterior también se pueden obtener submatrices, por ejemplo en la submatriz,
([1, 2],[4, 5]), $i$ va de $0$ a $2$ en la fila y $j$ de $1$ a $3$ en la columna, ósea,

```python

A[0:2, 1:3] # da array([[1, 2],
            #           [4, 5]])
# También            
A[2, 1:3]   # da array([7, 8])      
```

## Permutar filas y columnas
Para permutar filas (o columnas) se hace de la siguiente manera,
```python
A[[0,2]] = A[[2,0]]
```
Permutar columnas 1 and 3
```python
A[:,[0,2]] = A[:,[2,0]]
```

## Operaciones elementales
Sumas y restas se hacen elemento a elemento,
```python
A = arange(9).reshape(3,3) # arange crea array de 9 elementos, reshape lo convierte en matriz 3x3.
B = array([[2,1,3],[-1,2,-1],[3,1,1]])
A+B # da array([[2, 2, 5],
    #           [2, 6, 4],
    #           [9, 8, 9]])
    
A-B # da array([[-2,  0, -1],
    #           [ 4,  2,  6],
    #           [ 3,  6,  7]])
```
En la multiplicación y división numpy falla pues multiplica elemento a elemento $a_{ij}*b_{ij}$ y $a_{ij}/b_{ij}$,
```python
A*B # da array([[ 0,  1,  6], Esto NO es multiplicación matricial
    #           [-3,  8, -5],
    #           [18,  7,  8]])

A/B # da array([[ 0,  1,  0], Esto NO es division matricial o A*inv(B)
    #           [-3,  2, -5],
    #           [ 2,  7,  8]])
```
Numpy también cuenta con la instancia `numpy.matrix()` para poder hacer estas operaciones,
```python
M1 = matrix([[1,2,3],[ 4,5, 6],[7,8,9]])
M2 = matrix([[2,1,3],[-1,2,-1],[3,1,1]])

M1 + M2 # da igual que A + B  
M1 - M2 # da igual que A - B
M1 * M2 # da producto matricial de M1 y M2
M1 / M2 # da igual que A/B
```
Note que `A/B` y `M1/M2` no son definidos correctamente (estas operaciones hacen división elemento a elemento), pero se puede computar la inversa de la matriz creada con el array `A` mediante el uso del método `numpy.linalg.inv()`,
```python
inv(A)  # A es matriz singular (no tiene inversa, pues a11 = 0 es cero)

inv(B)  # da array([[-0.17647059, -0.11764706,  0.41176471],
        #           [ 0.11764706,  0.41176471,  0.05882353],
        #           [ 0.41176471, -0.05882353, -0.29411765]])

```
entonces la división matricial es,
```python
M1*inv(M2)     # da matrix([[ 1.29411765,  0.52941176, -0.35294118],
               #            [ 2.35294118,  1.23529412,  0.17647059],
               #            [ 3.41176471,  1.94117647,  0.70588235]])

```
En general, la multiplicación matricial de arrays se puede hacer con varios métodos: `numpy.matmul(), numpy.dot` y el operador `@`,
```python
matmul(A,B)    # si A y B son 2D Arrays
dot(A,B)       # si A y B son 2D Arrays, y producto punto si son 1D arrays
A@B            # igual que matmul o dot.
```
estos tres métodos son equivalentes.

Se puede transformar una array a matriz o viceversa,

```python
M1 = np.matrix(A) # dado que A es definido array.
A  = np.array(M1) # dado que M1 es definido Matrix.
```

In [ ]:
a=array()
a**2
b=matrix()
b**2
b*b

NameError: ignored

## Obtener propiedades de una matriz
Para calcular el determinante se usa el método `numpy.linalg.det()` (note que M1 y $A$ son singulares),
```python
det(A)     # da 0.0, la matriz A es singular y NO tiene inversa.
det(M1)    # da -9.5161973539299405e-16 este valor es muy pequeño ent M1 no tiene
           # inversa numérica (en algunas máquinas puede dar inv(M1)
           # pero con números grandes):
           #  matrix([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
           #          [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
           #          [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])
det(B) = 17.0
```
Matriz transpuesta de `M1`, note que $a_{ij}$ es cambiado por $a_{ji}$,
```python
transpose(M1) #  método de numpy
```
Obtener diagonal de la matriz,
```python
diagonal(M1)  # da array([1, 5, 9]), método de numpy
```
La diagonal del una matriz,
```python
diag(A)       # da array([1, 5, 9], método de numpy
```

Traza de la matriz o suma de les elementos de la diagonal.
```python
trace(M1)    # da sum(array([1, 5, 9])) = 15

triu(M1)     # Matriz triangular superior
tril(M1)     # Matriz triangular inferior
```
Para obtener la dimensión de la matriz, use,
```python
len(A)       # da 3, numero de filas de la matriz (en un vector da la dimensión)
A.shape      # da (3,3), la dimensión de la matriz.
```
## Solución de sistemas matriciales
Para resolver el sistema matricial $A\mathbf{x} = \mathbf{b}$ por cálculo de la matriz inversa:
```python
b = array([1,1,-1])
x = matmul(inv(B),b) # Multiplicación matricial si B y b tipo array.

b = matrix([1,1,-1])
x = inv(M2)*b        # Multiplicación matricial si M2 y b to tipo matrix.
```
También $A\mathbf{x} = \mathbf{b}$  con el método `numpy.solve()`,
```python
x = solve(M2,b)      # Más eficiente que el método anterior.
```

## Copias de un array
Note que para hacer una copia de un array o matriz no sirve  hacer `b = a`,
pues `b` solo apunta a la dirección de memoria de `a` (`b` es un alias de `a`) y al
modificar `b` se modifica `a`, veamos,
```python
b = a                # a es array([0,1,2,3,4,5,6,7,8,9])
b[0] = 5
print(a[0])          # da a[0] = 5
```
Mejor para crear una copia real de `a`, usar el comando `numpy.copy()`,
```python
b = np.copy(a)       # donde a es array([5,1,2,3,4,5,6,7,8,9])
b[0] = 0             # b es array([0,1,2,3,4,5,6,7,8,9])
print(a[0], b[0])    # da a[0] = 5 y b[0] = 0
```

## Eliminación gaussiana

Un primer método para resolver sistemas lineales de ecuaciones es la eliminación gaussiana. Este procedimiento consiste en un conjunto de pasos recursivos realizados para diagonalizar la matriz del problema.

Now, we shall describe the general procedure for Gaussian elimination:

**1.** Give an augmented matrix $\hat{A}=[A:\textbf{b}]$.

**2.** Find the first non-zero coefficient $a_{i1}$ associated to $x_1$. This element is called **pivot**.

**3.** Apply the operation $Swap(E_1,E_i)$. This guarantee the first row has a non-zero coefficient $a_{11}$.

**4.** Apply the operation $Comb(E_j,E_1,-a_{j1}/a_{11})$. This eliminates the coefficients associated to $x_1$ in all the rows but in the first one.

**5.** Repeat steps **2** to **4** but for the coefficients of $x_2$ and then $x_3$ and so up to $x_n$. When iterating the coefficients of $x_{k}$, do not take into account the first $k$-th rows as they are already sorted.

**6.** Once you obtain a diagonal form of the matrix, apply the operation $Lamb(E_n,1/a_{nn})$. This will make the coefficient of $x_n$ in the last equation equal to 1.

**7.** The final result should be an augmented matrix of the form:

$$\left[ \matrix{
a_{11} & a_{12} & \cdots & a_{1(n-1)} & a_{1n} & \vdots & \hat b_1 \\
0 & a_{22} & \cdots & a_{2(n-1)} & a_{2n} & \vdots & \hat b_2 \\
\vdots & \vdots &  & \vdots & \vdots & \vdots & \vdots \\
0 & 0 & \cdots & a_{(n-1)(n-1)} & a_{(n-1)n} & \vdots & \hat b_{n-1} \\
0 & 0 & \cdots & 0 & 1 & \vdots & \hat b_n
}\right]$$

**8.** The solution to the problem is then obtained through backward substitutions, i.e.

$$x_n = \hat b_n$$
$$ x_{n-1} =  \frac{\hat b_{n-1} + a_{(n-1)n}x_n}{a_{(n-1)(n-1)}}$$
$$\vdots$$
$$x_i = \frac{\hat b_i - \sum_{j=i+1}^n a_{ij}x_j}{a_{ii}}\ \ \ \ \mbox{for}\ \ \ i=n-1, n-2, \cdots, 1$$

**Ejercicio** Escriba tres rutinas que realicen, dada una matriz $ A $, las operaciones anteriores sobre matrices:

**row_lamb($i$, $ \lambda $, $ A $)**: $ i $ es la fila que se va a cambiar, $ \lambda $ el factor multiplicativo y A la matriz. Esta función debería devolver la nueva matriz con la operación realizada $ (\lambda E_i) \rightarrow (E_i) $.

**row_comb ($ i $, $ j $ $ \lambda $, $ A $)**: $ i $ es la fila que se cambiará, $ j $ la fila que se agregará, $ \lambda $ el factor multiplicativo y A la matriz. Esta función debería devolver la nueva matriz con la operación realizada $ (E_i + \lambda E_j) \rightarrow (E_i) $.

**row_swap ($ i $, $ j $, $ A $)**: $ i $ y $ j $ son las filas que se intercambian. Esta función debería devolver la nueva matriz con la operación realizada $ (E_i) \leftrightarrow (E_j) $.

In [ ]:
def row_lamb(i, lamb, A):
    M = np.copy(A)
    M[[i]] *= lamb
    return M

def row_comb(i, j, lamb, A):
    M = np.copy(A)
    M[[i]] += lamb * M[[j]]
    return M

def row_swap(i, j, A):
    M = np.copy(A)
    M[[i, j]] = M[[j, i]]
    return M

In [ ]:
#Gaussian Elimination
def Gaussian_Elimination( A0 ):
    #Making local copy of matrix
    A = np.copy(A0)
    #Detecting size of matrix
    n = len(A)

    #Sweeping all the columns in order to eliminate coefficients of the i-th variable
    for i in range( 0, n ):

        #Sweeping all the rows for the i-th column in order to find the first non-zero coefficient
        for j in range( i, n ):
            if A[i,j] != 0:
                #Normalization coefficient
                Norm = 1.0*A[i,j]
                break

        #Applying swap operation to put the non-zero coefficient in the i-th row
        A = row_swap( i, j, A )

        #Eliminating the coefficient associated to the i-th variable
        for j in range( i+1, n ):
            A = row_comb( j, i, -A[j,i]/Norm, A )

    #Normalizing n-th variable
    A = row_lamb( n-1, 1.0/A[n-1,n-1], A )

    #Finding solution
    x = np.zeros( n )
    x[n-1] = A[n-1,n]
    for i in range( n-1, -1, -1 ):
        x[i] = ( A[i,n] - sum(A[i,i+1:n]*x[i+1:n]) )/A[i,i]

    #Upper diagonal matrix and solutions x
    return A, x

In [ ]:
import numpy as np
M2 = np.array([[2.,1.,3],[-1.,2,-1],[3,1,1]])
b=np.array([1,1,-1])
M2b=np.array([[2.,1.,3,1],[-1.,2,-1,1],[3,1,1,-1]])
M2b

array([[ 2.,  1.,  3.,  1.],
       [-1.,  2., -1.,  1.],
       [ 3.,  1.,  1., -1.]])

In [ ]:
M2b=np.append(M2,b[:,None], axis=1)# agrega fila Otra para crear la matrix aumentada
M2b

array([[ 2.,  1.,  3.,  1.],
       [-1.,  2., -1.,  1.],
       [ 3.,  1.,  1., -1.]])

In [ ]:
Gaussian_Elimination(M2b)

(array([[ 2.        ,  1.        ,  3.        ,  1.        ],
        [ 0.        ,  2.5       ,  0.5       ,  1.5       ],
        [-0.        , -0.        ,  1.        ,  0.64705882]]),
 array([-0.70588235,  0.47058824,  0.64705882]))

In [ ]:
from numpy.linalg import *
from numpy import *
M2 = array([[2,1,3],[-1,2,-1],[3,1,1]])
b = matrix([1,1,-1])

## Determinante matricial

El determinante de una matriz es una cantidad escalar calculada para la matriz cuadrada. Esto proporciona información importante sobre la matriz de coeficientes de un sistema de ecuaciones lineales. Por ejemplo, cualquier sistema de ecuaciones $ n $ y $ n $ incógnitas tiene una solución única si el determinante asociado es distinto de cero. Esto también implica que el determinante permite evaluar si una matriz es singular o no singular.

A continuación, definiremos algunas propiedades de los determinantes que nos permitirán calcular los determinantes utilizando un código recursivo:

**1.** If $A = [a]$ is a $1\times 1$ matrix, its determinant is then $\det A = a$.

**2.** If $A$ is a $n\times n$ matrix, the minor matrix $M_{ij}$ is the determinant of the $(n-1)\times(n-1)$ matrix obtained by deleting the $i$th row and the $j$th column.

**3.** The cofactor $A_{ij}$ associated with $M_{ij}$ is defined by $A_{ij} = (-1)^{i+j}M_{ij}$.

**4.** The determinant of a $n\times n$ matrix $A$ is given by:

$$ \det A = \sum_{j=1}^n a_{ij}A_{ij} $$

or

$$ \det A = \sum_{i=1}^n a_{ij}A_{ij} $$

This is, it is possible to use both, a row or a column for calculating the determinant.

**Ejercicio** Escriba una función que saque el determinante de forma recursiva y compruebe con el determinante de numpy

In [ ]:
M1 = array( [[5,-4,0],[9,7,6],[0,2,5]] )

In [ ]:
import numpy as np
def dete(A):
    det=0
    if len(A)==1:
        det=A[0]
    elif len(A)==2:
        det=A[0][0]*A[1][1]-A[1][0]*A[0][1]
    else:
        B=np.delete(A,0,axis=1)
        for j in range(len(A)):
            C=np.delete(B,j,axis=0)
            det+=A[j][0]*(-1)**(j)*dete(C)
    return(det)

In [ ]:
import numpy as np
M2 = np.array([[0.,1,3],[1,2,-1],[3,1,1]])
dete(M2)

-19.0

In [ ]:

np.linalg.det(M2)

-18.999999999999996

## **Tarea**

obtenga el determinante apartir de Gaussian_Elimination

In [ ]:
dete(M2)

-13.0

In [ ]:
# 1. Al intercambiar dos filas o dos columnas de una matriz,
#su determinante cambia de signo.

#2.Cuando a una fila (o columna) de una matriz se le suma o resta una combinación
# lineal de otras filas (o columnas), el valor de su determinante no se altera.

#3.  Al multiplicar todos los elementos de una fila o una columna de una matriz por un número,
#el determinante de la matriz resultante es igual al de la original multiplicado por ese mismo número.

def Gaussian_Determinant(A0):
  A = np.copy(A0) #copia de la matriz inicializada
  n = len(A) #Longitud de la matriz
  d = 1 #contador del determinante

#Barre columnas y filas para encontrar coeficientes diferentes de 0 y eliminarlos
  for i in range(0,n):
    for j in range(i,n):
      if A[i,j]!=0:
        #Normaliza los coeficientes
        Norm=1.0*A[i,j]
        break

#Operación de cambio de fila (por #1 cambia el signo del determinante)
    if i!=j:
      d = -1.0*d
    A = row_swap(i,j,A)


#Operación de fila combinación lineal (#2)
    for j in range(i+1,n):
      A = row_comb(j,i,-A[j,i]/Norm,A)
      #determinante permanece invariable

 #Operación de fila multiplicación por escalar
  d = d*(A[n-1,n-1]) #3

  A = row_lamb(n-1,1.0/A[n-1,n-1],A)

#Calculo final del determinante
  for i in range(n):
    d = d*A[i,i]
  return d

Gaussian_Determinant(M2)

-19.0